### ISSUE TITLE
[Identity] Statement of Support from Citrix

### ISSUE THREAD

**Issue by anishathattai** [w3c/mediacapture-handle#14]
For us at Citrix MTOP (Microsoft Teams Optimization), screen-sharing is one of the most commonly requested features by our customers. Today, screen-sharing via Microsoft Teams allows sharing of any content on the local device. This has significant Security ramifications, and screen-sharing is therefore disabled by default (in order to prevent unintended data exposure). Capture Handle allows us to enable screen-sharing, inspect what the user has chosen to capture, and only allow captures of approved content to proceed.
 
We have a strong business need for Capture Handle and would like to see it shipped as soon as possible. We have prototyped based on it and found it to serve our needs. It's risky building features based on Origin Trial features. We would like to see it shipped soon, so that we may have the confidence necessary to invest the engineering effort of "productionizing" our prototype. We intend to do so as soon as the feature ships. Ideally, we'd like to see it shipped yesterday, but m101 would also be nice.

**Comment by jan-ivar** [comment]
This imported issue seems vendor specific rather than a W3C concern, so we should close this.

**Comment by eladalon1983** [comment]
I think it's good to document how Web-developers use (or intend to use) this feature, so that we build something that serves their needs and gains adoption. Here we have a significant company, serving a great many end-users, whose use-case maps onto [Use-case 3: Detecting Unintended or Unapproved Captures](https://github.com/w3c/mediacapture-handle/blob/main/identity/explainer.md#use-case-3-detecting-unintended-or-unapproved-captures). We may still wish to close this issue, as it requires no further action. But let's please record that it is, in fact, a relevant issue. Thank you for filing this, @anishathattai. Looking forward to seeing you successfully employ this feature!
