### ISSUE TITLE
What does capturehandlechange event do when cross documentation navigation happen?

### ISSUE THREAD

**Issue by xuesichao** [w3c/mediacapture-handle#74]
Hi, I see in the blog [Better tab sharing with Capture Handle](https://developer.chrome.com/docs/web-platform/capture-handle#capturing_side) :

>Monitor CaptureHandle changes by listening to "capturehandlechange" events on a MediaStreamTrack object. Changes happen when:
>
>- The captured web app calls navigator.mediaDevices.setCaptureHandleConfig().
>- A [cross-document navigation](https://chromium.googlesource.com/chromium/src/+/main/docs/navigation_concepts.md#Same_Document-and-Cross_Document-Navigations) occurs in the captured web app.

I found it not clear on what will be the value of `event.target.getCaptureHandle()` when cross-document navigation happens.
```
// When cross-document navigation happens
videoTrack.addEventListener('capturehandlechange', event => {
  captureHandle = event.target.getCaptureHandle();
  // What's the value of captureHandle?
});
```
Could you help clarify this? It seems the captureHandle will be `null` in this case? And when does this event gets triggered exactly? Is there a specific DOM event? Thank you.

**Comment by eladalon1983** [comment]
I think the spec can clarify this topic - see [here](https://www.w3.org/TR/capture-handle-identity/#events). Let me know if that helped.

**Comment by eladalon1983** [comment]
The capture handle is indeed reset, and you'll get no capture handle until the refreshed page loads to the point where it sets it again. I don't think we can avoid this atm, because we don't really know if the captured page will ever call setCaptureHandleConfig() again. But I believe you have a work-around available:
* Upon observing the change of capture handle from a permitted origin to null, pause remote transmission of the video.
* Hold off on any user-facing messaging for a few seconds.
* If the refreshed page ends up setting the permitted origin - great, it's a refresh and you can resume remote transmission of the stream.
* Otherwise, display some message to the user.

It's an imperfect solution - it will delay messages when they're needed, and occasionally it will show messages right before the page loads far enough to set the capure handle -  but that's what you can do with existing APIs. If you try this out, I would love to hear the empirical evidence of how well it worked.

Btw, you might be concerned that not all frames will be supressed, because the event might fire and be handled after some disallowed frames are captured and transmitted remotely. I had filed [this proposal](https://github.com/w3c/mediacapture-screen-share-extensions/issues/4) for it in the past. Since then, @tovepet has taken over this endeavor. I bet she'd love to get in touch with you and see if the solution she's working on could address your use case as well.

**Comment by xuesichao** [comment]
The work-around we have right now is very similar to your suggestion, the only difference is that instead of pausing remote transmission, we set the `track.enabled` to `disabled` when `captureHandle` is `null`, so the video stream is blank/black.

```js
stream.getTracks().forEach(track=> track.enabled = false)
```

>The capture handle is indeed reset, and you'll get no capture handle until the refreshed page loads to the point where it sets it again. 

That's exactly what I wanted to confirm. Not sure if this is a common knowledge for web developer when cross-document navigation happens, it seems so. It might be helpful to add this behavior to the blog here: https://developer.chrome.com/docs/web-platform/capture-handle#:~:text=A%20cross%2Ddocument%20navigation%20occurs%20in%20the%20captured%20web%20app.

For captured content switching. Since we manually set the `tract.enabled` to `false`, the result is quite similar to auto-pause  feature you are proposing. It will be way more reliable if we can detect it from dedicated browser APIs.

@eladalon1983 Thank you so much for your insights, you are very friendly and thoughtful.
